title: luska
author: Lucas Botelho
email: luska@riseup.net
description: > # this means to ignore newlines until "show_exerpts:"
  I'm 18 years old security analyst and student from Brazil. I like to 
  play CTFs and I also do some bug bounty and security research. I'm actually
  focused on Web and Mobile security. 
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: luskabol-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/luskabol
      icon: twitter-square
      color: cyan
    - url: https://luska.wtf
      icon: itch-io
      color: red
    - url: https://github.com/luskabol
      icon: github-square
      color: purple
    - url: https://linkedin.com/luska
      icon: linkedin
      color: blue

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
